name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Testing triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Modules and Run Jest
        working-directory: node-video-crime-miner
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test
      - run: echo "ğŸ This job's status is ${{ job.status }}."