name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Testing triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Run Node Test suite
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
      - run: |
          ls ${{ github.workspace }}
          cd node-video-crime-miner
          npm run test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3